site_name: Data Visualization
theme:
  name: material
nav:
  - Home: index.md
  - Matlab Plot: matlab-plot.md
  - Utils: extract-data.md
  - Palette: palette.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/basic.css
  - stylesheets/bootstrap.min.css
  - stylesheets/palette.css